// AUTO-GENERATED by scripts/fetch-notion.mjs. Do not edit by hand.
// Empty array => src/lib/design.ts uses its static fallback data.
import type { DesignProject } from "./design";

export const generated: DesignProject[] = [];
