// Build-time Notion fetch for the /design portfolio.
// Runs before `next build`. Queries the Notion "Design Cases" data source,
// downloads cover/gallery images into /public/design/<slug>/, and writes
// src/lib/design.generated.ts. If NOTION_TOKEN is absent (local dev without a
// token), it writes an empty list so design.ts falls back to its static data —
// the build never breaks.

import { writeFile, mkdir, rm } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

// Load .env.local for local runs (CI passes env directly). Real env wins.
const ENV_LOCAL = path.join(process.cwd(), ".env.local");
if (existsSync(ENV_LOCAL)) {
  for (const line of readFileSync(ENV_LOCAL, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m && !(m[1] in process.env)) {
      process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
    }
  }
}

const TOKEN = process.env.NOTION_TOKEN;
const DATA_SOURCE_ID = process.env.NOTION_DATA_SOURCE_ID;
const NOTION_VERSION = "2025-09-03";

const ROOT = path.resolve(process.cwd());
const PUBLIC_DESIGN = path.join(ROOT, "public", "design");
const OUT_TS = path.join(ROOT, "src", "lib", "design.generated.ts");

// Rotating placeholder gradients for cases without a cover image.
const GRADIENTS = [
  "from-sky-400 via-blue-500 to-indigo-600",
  "from-emerald-400 via-green-500 to-teal-600",
  "from-orange-400 via-amber-500 to-rose-500",
  "from-violet-400 via-purple-500 to-fuchsia-600",
  "from-cyan-400 via-sky-500 to-blue-600",
  "from-pink-400 via-rose-500 to-red-500",
  "from-slate-500 via-gray-600 to-zinc-700",
  "from-indigo-400 via-violet-500 to-purple-600",
];

function writeGenerated(projects) {
  const banner =
    "// AUTO-GENERATED by scripts/fetch-notion.mjs. Do not edit by hand.\n" +
    "// Empty array => src/lib/design.ts uses its static fallback data.\n";
  const body =
    'import type { DesignProject } from "./design";\n\n' +
    `export const generated: DesignProject[] = ${JSON.stringify(projects, null, 2)};\n`;
  return writeFile(OUT_TS, banner + body, "utf8");
}

// ── property readers ──
const plain = (prop) =>
  (prop?.title ?? prop?.rich_text ?? []).map((t) => t.plain_text).join("").trim();
const multi = (prop) => (prop?.multi_select ?? []).map((o) => o.name);
const checkbox = (prop) => Boolean(prop?.checkbox);
const number = (prop) => (typeof prop?.number === "number" ? prop.number : 0);
const fileUrls = (prop) =>
  (prop?.files ?? [])
    .map((f) => f?.file?.url ?? f?.external?.url)
    .filter(Boolean);

// YouTube watch/short/embed URL -> canonical embed URL. Returns null for non-YouTube.
function youtubeEmbed(url) {
  try {
    const u = new URL(url);
    const host = u.hostname.replace(/^www\./, "");
    let id;
    if (host === "youtu.be") id = u.pathname.slice(1);
    else if (host.endsWith("youtube.com")) {
      if (u.pathname.startsWith("/embed/")) id = u.pathname.split("/")[2];
      else if (u.pathname.startsWith("/shorts/")) id = u.pathname.split("/")[2];
      else id = u.searchParams.get("v");
    }
    return id ? `https://www.youtube.com/embed/${id}` : null;
  } catch {
    return null;
  }
}

// ASCII-only slug. Non-ASCII (e.g. Korean) is dropped — GitHub Pages 404s on
// non-ASCII file paths, so sub-case routes must stay ASCII. Callers fall back to
// an index suffix when the result is empty.
function slugify(s) {
  return String(s)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function extFromUrl(url, fallback = ".jpg") {
  try {
    const p = new URL(url).pathname;
    const m = p.match(/\.(jpg|jpeg|png|webp|gif|svg|avif|mp4|mov|webm|m4v)$/i);
    return m ? m[0].toLowerCase() : fallback;
  } catch {
    return fallback;
  }
}

// Optional sharp for build-time image optimization (raster -> WebP, resized).
// Absent locally? Fall back to writing the original bytes.
let sharp = null;
try {
  sharp = (await import("sharp")).default;
} catch {
  console.warn("[fetch-notion] sharp not installed — images saved unoptimized.");
}

async function download(url, destDir, baseName) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`download ${res.status} ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const ext = extFromUrl(url);

  if (sharp && /\.(png|jpe?g|gif|webp)$/.test(ext)) {
    try {
      const animated = ext === ".gif" || ext === ".webp";
      const img = sharp(buf, { animated });
      const meta = await img.metadata();
      const width = Math.min(meta.width ?? 1600, animated ? 900 : 1600);
      const out = await img
        .resize({ width, withoutEnlargement: true })
        .webp({ quality: animated ? 70 : 80, effort: 4 })
        .toBuffer();
      // keep the original if conversion doesn't actually shrink it
      if (out.length < buf.length) {
        const file = `${baseName}.webp`;
        await writeFile(path.join(destDir, file), out);
        return file;
      }
    } catch (e) {
      console.warn(`[fetch-notion] optimize failed for ${baseName}${ext}: ${e.message}`);
    }
  }

  const file = `${baseName}${ext}`;
  await writeFile(path.join(destDir, file), buf);
  return file;
}

const rt = (arr) => (arr ?? []).map((t) => t.plain_text).join("").trim();

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Notion request with 429 handling. Recursing into columns fans out many GETs;
// the public API rate-limits (~3 req/s), so honor Retry-After and back off.
async function notionFetch(url, init, label = "request") {
  for (let attempt = 0; attempt < 6; attempt++) {
    const res = await fetch(url, init);
    if (res.status === 429) {
      const retryAfter = Number(res.headers.get("retry-after")) || 2 ** attempt;
      await sleep((retryAfter + 0.5) * 1000);
      continue;
    }
    if (!res.ok) throw new Error(`Notion ${label} ${res.status}: ${await res.text()}`);
    return res.json();
  }
  throw new Error(`Notion ${label} failed after retries (429): ${url}`);
}

async function notionGet(url) {
  return notionFetch(
    url,
    { headers: { Authorization: `Bearer ${TOKEN}`, "Notion-Version": NOTION_VERSION } },
    "GET"
  );
}

// Fetch all children of a block/page, following pagination.
async function fetchChildren(blockId) {
  const blocks = [];
  let cursor;
  do {
    const q = cursor ? `?start_cursor=${cursor}&page_size=100` : "?page_size=100";
    const json = await notionGet(`https://api.notion.com/v1/blocks/${blockId}/children${q}`);
    blocks.push(...json.results);
    cursor = json.has_more ? json.next_cursor : undefined;
  } while (cursor);
  return blocks;
}

// Fetch a page's body blocks, download inline images, and map to DesignBlock[].
// Recurses into layout containers (column_list/column/toggle/synced_block) so images
// placed inside Notion multi-column layouts are captured, not silently dropped.
// Any inline child databases found get their block ids pushed onto `childDbs` (out-param)
// so the caller can pull their rows in as separate sub-cases.
async function fetchBody(pageId, dir, slug, childDbs = []) {
  const out = [];
  const ctx = { imgN: 0 };

  async function walk(blocks) {
    for (const b of blocks) {
      switch (b.type) {
        case "heading_1":
          out.push({ type: "heading", level: 1, text: rt(b.heading_1.rich_text) });
          break;
        case "heading_2":
          out.push({ type: "heading", level: 2, text: rt(b.heading_2.rich_text) });
          break;
        case "heading_3":
          out.push({ type: "heading", level: 3, text: rt(b.heading_3.rich_text) });
          break;
        case "paragraph": {
          const text = rt(b.paragraph.rich_text);
          if (text) out.push({ type: "paragraph", text });
          if (b.has_children) await walk(await fetchChildren(b.id));
          break;
        }
        case "bulleted_list_item":
          out.push({ type: "bullet", text: rt(b.bulleted_list_item.rich_text) });
          if (b.has_children) await walk(await fetchChildren(b.id));
          break;
        case "numbered_list_item":
          out.push({ type: "number", text: rt(b.numbered_list_item.rich_text) });
          if (b.has_children) await walk(await fetchChildren(b.id));
          break;
        case "quote":
          out.push({ type: "quote", text: rt(b.quote.rich_text) });
          if (b.has_children) await walk(await fetchChildren(b.id));
          break;
        case "callout":
          out.push({ type: "quote", text: rt(b.callout.rich_text) });
          if (b.has_children) await walk(await fetchChildren(b.id));
          break;
        case "divider":
          out.push({ type: "divider" });
          break;
        case "image": {
          const src = b.image?.file?.url ?? b.image?.external?.url;
          if (!src) break;
          ctx.imgN += 1;
          const file = await download(src, dir, `body-${ctx.imgN}`);
          const caption = rt(b.image.caption);
          out.push({ type: "image", src: `/design/${slug}/${file}`, ...(caption ? { caption } : {}) });
          break;
        }
        case "video": {
          const src = b.video?.external?.url ?? b.video?.file?.url;
          if (!src) break;
          const embedUrl = youtubeEmbed(src);
          const caption = rt(b.video.caption);
          if (embedUrl) {
            out.push({ type: "video", provider: "youtube", embedUrl, ...(caption ? { caption } : {}) });
          } else if (b.video?.file?.url) {
            // uploaded video file: download and serve locally
            try {
              ctx.vidN = (ctx.vidN ?? 0) + 1;
              const file = await download(src, dir, `video-${ctx.vidN}`);
              out.push({ type: "videofile", src: `/design/${slug}/${file}`, ...(caption ? { caption } : {}) });
            } catch (e) {
              console.warn(`[fetch-notion] video download failed (${slug}): ${e.message}`);
            }
          }
          break;
        }
        // External links (e.g. the live service URL) — bookmark/embed/link_preview.
        case "bookmark": {
          const url = b.bookmark?.url;
          if (!url) break;
          const title = rt(b.bookmark.caption);
          out.push({ type: "link", url, ...(title ? { title } : {}) });
          break;
        }
        case "link_preview": {
          const url = b.link_preview?.url;
          if (url) out.push({ type: "link", url });
          break;
        }
        case "embed": {
          const url = b.embed?.url;
          if (!url) break;
          const yt = youtubeEmbed(url);
          if (yt) {
            const caption = rt(b.embed.caption);
            out.push({ type: "video", provider: "youtube", embedUrl: yt, ...(caption ? { caption } : {}) });
          } else {
            const title = rt(b.embed.caption);
            out.push({ type: "link", url, ...(title ? { title } : {}) });
          }
          break;
        }
        case "code": {
          const text = rt(b.code.rich_text);
          if (text) out.push({ type: "code", text, ...(b.code.language ? { language: b.code.language } : {}) });
          break;
        }
        case "child_database":
          childDbs.push(b.id); // block id == database id; resolved to a data source later
          break;
        // multi-column layout: emit a gallery block that preserves the Notion column
        // count so the site renders the same N-wide grid. Images across all columns are
        // collected in reading order. If the columns hold no images, fall back to walking
        // them inline (so any text still shows).
        case "column_list": {
          const columns = b.has_children ? await fetchChildren(b.id) : [];
          const images = [];
          // Collect images at any nesting depth inside a column (e.g. indented
          // under a list item), in reading order.
          async function collectImages(blocks) {
            for (const k of blocks) {
              if (k.type === "image") {
                const src = k.image?.file?.url ?? k.image?.external?.url;
                if (!src) continue;
                ctx.imgN += 1;
                const file = await download(src, dir, `body-${ctx.imgN}`);
                const caption = rt(k.image.caption);
                images.push({ src: `/design/${slug}/${file}`, ...(caption ? { caption } : {}) });
              } else if (k.has_children) {
                await collectImages(await fetchChildren(k.id));
              }
            }
          }
          for (const col of columns) {
            if (col.has_children) await collectImages(await fetchChildren(col.id));
          }
          if (images.length) out.push({ type: "gallery", cols: columns.length || images.length, images });
          else if (columns.length) await walk(columns);
          break;
        }
        // other containers: no layout of their own — recurse inline in reading order.
        case "column":
        case "toggle":
        case "synced_block": {
          if (b.has_children) await walk(await fetchChildren(b.id));
          break;
        }
        default:
          break; // skip unsupported block types
      }
    }
  }

  await walk(await fetchChildren(pageId));
  return groupLabeledImages(out);
}

// Post-process: a run of numbered-label → image pairs (Notion "1. caption" above a
// full-width image, repeated) becomes a 2-column gallery with each label as the image's
// caption. Leaves single labeled images and existing galleries untouched.
function groupLabeledImages(blocks) {
  const out = [];
  let i = 0;
  while (i < blocks.length) {
    const run = [];
    let j = i;
    while (j + 1 < blocks.length && blocks[j].type === "number" && blocks[j + 1].type === "image") {
      run.push({ label: blocks[j].text, img: blocks[j + 1] });
      j += 2;
    }
    if (run.length >= 2) {
      out.push({
        type: "gallery",
        cols: 2,
        images: run.map((r) => {
          const caption = r.img.caption || r.label;
          return { src: r.img.src, ...(caption ? { caption } : {}) };
        }),
      });
      i = j;
    } else {
      out.push(blocks[i]);
      i += 1;
    }
  }
  return out;
}

// Resolve a database id to its first data source id (Notion API 2025-09-03).
async function firstDataSourceId(databaseId) {
  const json = await notionGet(`https://api.notion.com/v1/databases/${databaseId}`);
  return json.data_sources?.[0]?.id ?? null;
}

// Year from a Notion date property, e.g. "2014-01-01" -> "2014".
function yearOf(prop) {
  const start = prop?.date?.start;
  return start ? String(start).slice(0, 4) : "";
}

async function queryAll(dataSourceId = DATA_SOURCE_ID) {
  const pages = [];
  let cursor;
  do {
    const json = await notionFetch(
      `https://api.notion.com/v1/data_sources/${dataSourceId}/query`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${TOKEN}`,
          "Notion-Version": NOTION_VERSION,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(cursor ? { start_cursor: cursor, page_size: 100 } : { page_size: 100 }),
      },
      "query"
    );
    pages.push(...json.results);
    cursor = json.has_more ? json.next_cursor : undefined;
  } while (cursor);
  return pages;
}

async function main() {
  if (!TOKEN || !DATA_SOURCE_ID) {
    console.log("[fetch-notion] NOTION_TOKEN/NOTION_DATA_SOURCE_ID not set — using static fallback.");
    await writeGenerated([]);
    return;
  }

  console.log("[fetch-notion] querying Notion data source…");
  const pages = await queryAll();

  // fresh image dir each build
  if (existsSync(PUBLIC_DESIGN)) await rm(PUBLIC_DESIGN, { recursive: true, force: true });
  await mkdir(PUBLIC_DESIGN, { recursive: true });

  const projects = [];
  const subProjects = []; // nested sub-cases (hidden from grid, own routes)
  let subColor = 1; // gradient index for sub-cases

  for (const page of pages) {
    const p = page.properties;
    if (!checkbox(p["Published"])) continue;

    const slug = plain(p["Slug"]);
    if (!slug) {
      console.warn(`[fetch-notion] skip page ${page.id} — missing Slug`);
      continue;
    }

    const idx = projects.length;
    const emoji = page.icon?.type === "emoji" ? page.icon.emoji : "🎨";
    const dir = path.join(PUBLIC_DESIGN, slug);
    await mkdir(dir, { recursive: true });

    const title = { ko: plain(p["Title KO"]), en: plain(p["Title EN"]) || plain(p["Title KO"]) };

    // cover
    let cover;
    const coverSrc = fileUrls(p["Cover"])[0];
    if (coverSrc) {
      const file = await download(coverSrc, dir, "cover");
      cover = `/design/${slug}/${file}`;
    }

    // gallery
    const gallery = [];
    const gallerySrc = fileUrls(p["Gallery"]);
    for (let i = 0; i < gallerySrc.length; i++) {
      const file = await download(gallerySrc[i], dir, `gallery-${i + 1}`);
      gallery.push(`/design/${slug}/${file}`);
    }

    // page body (text + inline images + YouTube + code, in order); collect inline DBs
    const childDbs = [];
    const body = await fetchBody(page.id, dir, slug, childDbs);

    // thumbnail fallback: first body image when no Cover set
    if (!cover) {
      const firstImg = body.find((b) => b.type === "image");
      if (firstImg) cover = firstImg.src;
    }

    // nested sub-cases: each inline-DB row becomes its own routed detail page
    const subpages = [];
    for (const dbId of childDbs) {
      const dsId = await firstDataSourceId(dbId);
      if (!dsId) continue;
      const rows = await queryAll(dsId);
      for (let i = 0; i < rows.length; i++) {
        const row = rows[i];
        const rp = row.properties;
        const name = plain(rp["Name"]) || `${title.ko || slug} ${i + 1}`;
        const subSlug = `${slug}-${slugify(name) || i + 1}`;
        const subDir = path.join(PUBLIC_DESIGN, subSlug);
        await mkdir(subDir, { recursive: true });

        const subChildDbs = [];
        const subBody = await fetchBody(row.id, subDir, subSlug, subChildDbs);

        // Inline databases nested inside a sub-case don't get their own routes;
        // fold each of their rows into the sub-case body (heading + content).
        for (const nestedDbId of subChildDbs) {
          const nestedDsId = await firstDataSourceId(nestedDbId);
          if (!nestedDsId) continue;
          const nestedRows = await queryAll(nestedDsId);
          for (let k = 0; k < nestedRows.length; k++) {
            const nr = nestedRows[k];
            const nName = plain(nr.properties["Name"]);
            if (nName) subBody.push({ type: "heading", level: 3, text: nName });
            // own asset dir so image filenames can't collide with the sub-case's
            const nSlug = `${subSlug}--n${k + 1}`;
            const nDir = path.join(PUBLIC_DESIGN, nSlug);
            await mkdir(nDir, { recursive: true });
            const nBody = await fetchBody(nr.id, nDir, nSlug);
            subBody.push(...nBody);
          }
        }

        let subCover;
        const rowCover = fileUrls(rp["Cover"])[0];
        if (rowCover) {
          const f = await download(rowCover, subDir, "cover");
          subCover = `/design/${subSlug}/${f}`;
        }
        if (!subCover) {
          const fi = subBody.find((b) => b.type === "image");
          if (fi) subCover = fi.src;
        }

        const subEmoji = row.icon?.type === "emoji" ? row.icon.emoji : emoji;
        const subGradient = GRADIENTS[subColor++ % GRADIENTS.length];
        const subTitle = { ko: name, en: name };
        const firstPara = subBody.find((b) => b.type === "paragraph");
        const sum = firstPara ? firstPara.text.slice(0, 120) : "";

        subProjects.push({
          slug: subSlug,
          year: yearOf(rp["Work Period"]),
          cover: subCover,
          gradient: subGradient,
          emoji: subEmoji,
          role: { ko: "", en: "" },
          title: subTitle,
          summary: { ko: sum, en: sum },
          overview: { ko: "", en: "" },
          tags: multi(rp["Tags"]),
          ...(subBody.length ? { body: subBody } : {}),
          parent: { slug, title },
          hidden: true,
        });
        subpages.push({ slug: subSlug, title: subTitle, cover: subCover, gradient: subGradient, emoji: subEmoji });
      }
    }

    projects.push({
      slug,
      year: plain(p["Year"]),
      order: number(p["Order"]),
      cover,
      gradient: GRADIENTS[idx % GRADIENTS.length],
      emoji,
      role: { ko: plain(p["Role KO"]), en: plain(p["Role EN"]) || plain(p["Role KO"]) },
      title,
      summary: { ko: plain(p["Summary KO"]), en: plain(p["Summary EN"]) || plain(p["Summary KO"]) },
      overview: { ko: plain(p["Overview KO"]), en: plain(p["Overview EN"]) || plain(p["Overview KO"]) },
      tags: multi(p["Tags"]),
      ...(gallery.length ? { gallery } : {}),
      ...(body.length ? { body } : {}),
      ...(subpages.length ? { subpages } : {}),
    });
  }

  projects.sort((a, b) => a.order - b.order);
  projects.forEach((p) => delete p.order); // strip helper field

  const all = [...projects, ...subProjects];
  await writeGenerated(all);
  console.log(
    `[fetch-notion] wrote ${projects.length} published case(s) + ${subProjects.length} sub-case(s).`
  );
}

main().catch((err) => {
  console.error("[fetch-notion] error:", err.message);
  process.exit(1);
});
