// Build-time Notion fetch for the /design portfolio.
// Runs before `next build`. Queries the Notion "Design Cases" data source,
// downloads cover/gallery images into /public/design/<slug>/, and writes
// src/lib/design.generated.ts. If NOTION_TOKEN is absent (local dev without a
// token), it writes an empty list so design.ts falls back to its static data —
// the build never breaks.

import { writeFile, mkdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const TOKEN = process.env.NOTION_TOKEN;
const DATA_SOURCE_ID = process.env.NOTION_DATA_SOURCE_ID;
const NOTION_VERSION = "2025-09-03";

const ROOT = path.resolve(process.cwd());
const PUBLIC_DESIGN = path.join(ROOT, "public", "design");
const OUT_TS = path.join(ROOT, "src", "lib", "design.generated.ts");

// Rotating placeholder gradients for cases without a cover image.
const GRADIENTS = [
  "from-sky-400 via-blue-500 to-indigo-600",
  "from-emerald-400 via-green-500 to-teal-600",
  "from-orange-400 via-amber-500 to-rose-500",
  "from-violet-400 via-purple-500 to-fuchsia-600",
  "from-cyan-400 via-sky-500 to-blue-600",
  "from-pink-400 via-rose-500 to-red-500",
  "from-slate-500 via-gray-600 to-zinc-700",
  "from-indigo-400 via-violet-500 to-purple-600",
];

function writeGenerated(projects) {
  const banner =
    "// AUTO-GENERATED by scripts/fetch-notion.mjs. Do not edit by hand.\n" +
    "// Empty array => src/lib/design.ts uses its static fallback data.\n";
  const body =
    'import type { DesignProject } from "./design";\n\n' +
    `export const generated: DesignProject[] = ${JSON.stringify(projects, null, 2)};\n`;
  return writeFile(OUT_TS, banner + body, "utf8");
}

// ── property readers ──
const plain = (prop) =>
  (prop?.title ?? prop?.rich_text ?? []).map((t) => t.plain_text).join("").trim();
const multi = (prop) => (prop?.multi_select ?? []).map((o) => o.name);
const checkbox = (prop) => Boolean(prop?.checkbox);
const number = (prop) => (typeof prop?.number === "number" ? prop.number : 0);
const fileUrls = (prop) =>
  (prop?.files ?? [])
    .map((f) => f?.file?.url ?? f?.external?.url)
    .filter(Boolean);

function extFromUrl(url, fallback = ".jpg") {
  try {
    const p = new URL(url).pathname;
    const m = p.match(/\.(jpg|jpeg|png|webp|gif|svg|avif)$/i);
    return m ? m[0].toLowerCase() : fallback;
  } catch {
    return fallback;
  }
}

async function download(url, destDir, baseName) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`download ${res.status} ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const file = `${baseName}${extFromUrl(url)}`;
  await writeFile(path.join(destDir, file), buf);
  return file;
}

async function queryAll() {
  const pages = [];
  let cursor;
  do {
    const res = await fetch(
      `https://api.notion.com/v1/data_sources/${DATA_SOURCE_ID}/query`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${TOKEN}`,
          "Notion-Version": NOTION_VERSION,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(cursor ? { start_cursor: cursor, page_size: 100 } : { page_size: 100 }),
      }
    );
    if (!res.ok) {
      throw new Error(`Notion query failed ${res.status}: ${await res.text()}`);
    }
    const json = await res.json();
    pages.push(...json.results);
    cursor = json.has_more ? json.next_cursor : undefined;
  } while (cursor);
  return pages;
}

async function main() {
  if (!TOKEN || !DATA_SOURCE_ID) {
    console.log("[fetch-notion] NOTION_TOKEN/NOTION_DATA_SOURCE_ID not set — using static fallback.");
    await writeGenerated([]);
    return;
  }

  console.log("[fetch-notion] querying Notion data source…");
  const pages = await queryAll();

  // fresh image dir each build
  if (existsSync(PUBLIC_DESIGN)) await rm(PUBLIC_DESIGN, { recursive: true, force: true });
  await mkdir(PUBLIC_DESIGN, { recursive: true });

  const projects = [];
  for (const page of pages) {
    const p = page.properties;
    if (!checkbox(p["Published"])) continue;

    const slug = plain(p["Slug"]);
    if (!slug) {
      console.warn(`[fetch-notion] skip page ${page.id} — missing Slug`);
      continue;
    }

    const idx = projects.length;
    const emoji = page.icon?.type === "emoji" ? page.icon.emoji : "🎨";
    const dir = path.join(PUBLIC_DESIGN, slug);
    await mkdir(dir, { recursive: true });

    // cover
    let cover;
    const coverSrc = fileUrls(p["Cover"])[0];
    if (coverSrc) {
      const file = await download(coverSrc, dir, "cover");
      cover = `/design/${slug}/${file}`;
    }

    // gallery
    const gallery = [];
    const gallerySrc = fileUrls(p["Gallery"]);
    for (let i = 0; i < gallerySrc.length; i++) {
      const file = await download(gallerySrc[i], dir, `gallery-${i + 1}`);
      gallery.push(`/design/${slug}/${file}`);
    }

    projects.push({
      slug,
      year: plain(p["Year"]),
      order: number(p["Order"]),
      cover,
      gradient: GRADIENTS[idx % GRADIENTS.length],
      emoji,
      role: { ko: plain(p["Role KO"]), en: plain(p["Role EN"]) || plain(p["Role KO"]) },
      title: { ko: plain(p["Title KO"]), en: plain(p["Title EN"]) || plain(p["Title KO"]) },
      summary: { ko: plain(p["Summary KO"]), en: plain(p["Summary EN"]) || plain(p["Summary KO"]) },
      overview: { ko: plain(p["Overview KO"]), en: plain(p["Overview EN"]) || plain(p["Overview KO"]) },
      tags: multi(p["Tags"]),
      ...(gallery.length ? { gallery } : {}),
    });
  }

  projects.sort((a, b) => a.order - b.order);
  projects.forEach((p) => delete p.order); // strip helper field

  await writeGenerated(projects);
  console.log(`[fetch-notion] wrote ${projects.length} published case(s).`);
}

main().catch((err) => {
  console.error("[fetch-notion] error:", err.message);
  process.exit(1);
});
